# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1118d3e26dae42832c90127192c15230e83327f3c7cdc9bdee9a735b33d6736259916892b1bc6271b2fe7c4bb3c18beabee20702aa8d8454182f207f230599ba

test:
  secret_key_base: aedd47d333a48be1d65703dd540d418772f5233ec91ab0c803d931ebbc2450a3313958c5fb33c98c82f62bdd2ab460334058db2de7f13d5ed16b73634f2129c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
